version: '3.8'
services:
  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"
    environment:
      - GROBID_MAX_CONNECTIONS=10
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070"]
      interval: 10s
      timeout: 5s
      retries: 5
